services:
  redis:
    image: redis:alpine
    container_name: OnlyJsAcademyFullStackDevelopmentTraineeRedis
    networks:
      - onlyjs-academy
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  postgres:
    image: postgres:15
    container_name: OnlyJsAcademyFullStackDevelopmentTraineePostgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "104039"
      POSTGRES_DB: proteinshopbackend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - onlyjs-academy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  api:
    build: ./apps/api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./apps/api/.env
    networks:
      - onlyjs-academy
    restart: unless-stopped

  web:
    build: ./apps/web
    depends_on:
      - api
    networks:
      - onlyjs-academy
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web
    networks:
      - onlyjs-academy
    restart: unless-stopped
    volumes:
      - nginx_logs:/var/log/nginx
      # HTTPS için: domain alındığında certbot volume'unu aç
      # - certbot_data:/etc/letsencrypt

networks:
  onlyjs-academy:
    driver: bridge
    name: onlyjs-academy

volumes:
  postgres_data:
  nginx_logs:
  # certbot_data:
